config/routes.rb
Rails.application.routes.draw do


  devise_for :admins

  resources :posts do
    resources :comments
  end

  root 'posts#index'
  get '/about', to: 'posts#about'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_admin!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
  @post = Post.find(param[:post_id])
  @comment = @post.comments.create(params[:comment].permit(:name, :body))
end

def create
  @post = Post.find(param[:post_id])
  @comment = @post.comments.create(params[:comment].permit(:name, :body))
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_admin!

  def about
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
      if @post.save
        redirect_to @post
      else
        render 'new'
      end
    end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to root_path
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Blog</title>


    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>


    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="js/jquery.readmore-readless.js" type="text/javascript"></script>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  </head>
  <body>




    <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <% if alert.present? %>
    <div class="alert alert-dismissable alert-warning">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= alert %>
    </div>
    <% end %>
<div class="container-fluid">


    <%= yield %>
</div>

  </body>
  </html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

<% if @post.errors.any? %>
  <div class="errors">
    <h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control', rows: 10 %>
</div>

<div class="form-group">
  <%= f.submit %>
</div>

<%= link_to 'Cancel', posts_path %>
<% end %>

app/views/posts/about.html.erb
<p>Well, Where to begin... My name is Travis and I am a newly</p>

app/views/posts/edit.html.erb
  <%= render 'form' %>

app/views/posts/index.html.erb
<div id="sidebar" class="col-md-3 visible-md visible-lg" >

  <header id="header">
    <%= image_tag ('profile_pic.jpg'), id: "logo" %>
    <ul class="sidebar-links">
      <li id="sidebar-header">Travis Eubanks</li>
      <li><%= link_to "My Blog", posts_path %></li>
      <li><%= link_to "About", "#" %></li>
    </ul>

    <ul class="sidebar-links">
      <li id="social">Social</li>
      <li><%= link_to "Twitter", "https://twitter.com/teubanks13" %></li>
      <li><%= link_to "Github", "https://github.com/eubanksanator" %></li>
      <li><%= link_to "LinkedIn", "https://www.linkedin.com/in/traviseubanks" %></li>
          <% if admin_signed_in? %>
      <li><%= link_to "New Post", new_post_path %></li>
      <li><%= link_to "Sign Out", destroy_admin_session_path, method: 'delete' %></li>
          <% end %>
    </ul>
  </header>
</div><!--ends sidebar -->


<div class="panel-background">
  <div class="panel col-xs-12 col-sm-8 col-md-offset-3 col-md-9">
    <% @posts.each do |post| %>
    <h3 class="panel-title"><%= link_to post.title, post %></h3>
    <div class="post-date">
      <small><%= post.created_at.strftime("%B, %d, %Y") %></small>
    </div>
    <!-- WANT TO ADD COMMENTS INTO THE POST PANEL -->
    <div class="panel-body">
      <% if post.body.length > 150 %>
      <%= truncate(post.body, length: 150) %> <%= link_to 'read more', post_path(post) %>
      <% else %>
      <%= post.body %>
      <% end %>
      <hr>
    </div>
    <% end %>
  </div>
</div>





<script>
  var main = function() {
    $('#sidebar-title').click(function() {
      var $icon = $(this).find('i');
      if ($icon.hasClass('fa-chevron-down')) {
        $icon.removeClass('fa-chevron-down').addClass('fa-chevron-up');
      } else {
        $icon.addClass('fa-chevron-down').removeClass('fa-chevron-up');
      }
      $( "#sidebar" ).slideToggle( "slow" );
    });
  };
  $(document).ready(main);


</script>

app/views/posts/new.html.erb
  <h1>New Post</h1>

    <%= render 'form' %>

app/views/posts/show.html.erb
<div class="col-md-offset-2 col-md-7">

  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
  </p>

  <p class="panel-body well">
    <%= @post.body %>
  </p>

  <% if current_admin == Admin.first  %>
    <button class="btn btn-success"><%= link_to 'Edit', edit_post_url %></button>
    <button class="btn btn-danger"><%= link_to 'Delete', post_url, method: :delete, data: {confirm: "Are you sure you want to delete this post?" } %></button>
  <% end %>

    <button class="btn"><%= link_to 'Back', :back %></button>
</div>